apiVersion: v1
kind: Service
metadata:
  name: eqd-cp1-website-service
spec:
  type: NodePort
  selector:
    app: eqd-cp1-website
  ports:
    - protocol: TCP
      port: 80   # Port on which the service listens internally
      targetPort: 80  # Port on which the application inside the container is running
      nodePort: 30008  # External port on which the service is exposed
